# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Support for 16 KB page sizes (Android 15+ requirement)
android.bundle.enable16kbalignment=true
android.useNewApkCreator=true
android.packaging.jniLibs.useLegacyPackaging=false
android.extractNativeLibs=true
